# Generated by Django 5.1.1 on 2024-10-05 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechareservacion', models.DateField(max_length=50, verbose_name='Fechareservacion')),
                ('clientereservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('habitacionreservacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'reservacion',
                'verbose_name_plural': 'reservaciones',
                'db_table': 'reservacion',
                'ordering': ['-id'],
            },
        ),
    ]
