# Generated by Django 5.1.1 on 2024-10-05 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrohabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.DateTimeField(max_length=50, verbose_name='Entrada')),
                ('salida', models.DateTimeField(max_length=50, verbose_name='Salida')),
                ('fecha', models.DateField(max_length=50, verbose_name='Fecha')),
                ('clienteregistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('habitacionregistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitaciones.habitacion')),
            ],
            options={
                'verbose_name': 'registrohabitacion',
                'verbose_name_plural': 'registrohabitaciones',
                'db_table': 'registrohabitacion',
                'ordering': ['-id'],
            },
        ),
    ]
