# Generated by Django 5.1.1 on 2024-10-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('habitaciones', '0001_initial'),
        ('registro', '0002_remove_registrohabitacion_fecha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registrohabitacion',
            new_name='registrohabitaciones',
        ),
    ]
