# Generated by Django 5.1.1 on 2024-10-05 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_rename_registrohabitacion_registrohabitaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohabitaciones',
            name='salida',
            field=models.DateTimeField(max_length=50, null=True, verbose_name='Salida'),
        ),
    ]
